apiVersion: v1
kind: Service
metadata:
  name: platformservice-np
spec:
  type: NodePort
  selector:
    app: platformservice
  ports:
  - name: platformservice
    port: 80
    targetPort: 80
    protocol: TCP

    
