apiVersion: apps/v1
kind: Deployment
metadata:
  name: platformservice
spec:
  selector:
    matchLabels:
      app: platformservice
  replicas: 1
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
      - name: platformservice
        image: giao5fs/platform_service:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:  
  name: platformservice-clusterip
spec:
  selector:    
    app: platformservice
  type: ClusterIP
  ports:  
  - name: platformservice
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: platformservice-np
spec:
  type: NodePort
  selector:
    app: platformservice
  ports:
  - name: platformservice
    port: 80
    targetPort: 80
    protocol: TCP